### ISSUE TITLE
Caps lock won't work as hyper key 

### ISSUE THREAD

**Issue by lawsonguilbeau** [mxstbr/karabiner#20] opened 2024-04-18 02:11 UTC
I downloaded the repository, and followed all of the instructions in the readme.md file. However, what I am wondering how to fix, is why the caps lock key will only work as escape, and not as the hyper key. I am aware that tapping it once will count as the escape key, but if I hold it, it does not activate the hyper key setup like it should. I also cannot add preconfigured extensions from the karabiner elements complex modifications website.

**Comment by Jona630** [comment] 2024-04-18 03:10
I was having the same issue with a custom Raycast cmd (hyperkey + H), but it works wonder with the examples from `rules.ts`

For example `caps_lock + r + p` will throw confetti from Raycast, but only by pressing and holding all keys in that order

**Comment by sluzhynskyi** [comment] 2024-04-18 09:24
@lawsonguilbeau Had the same issue, to solve just give the Karabiner Full Disk access, SystemPref -> PrivacySecurity
<img width="713" alt="SCR-20240418-ldyf" src="https://github.com/mxstbr/karabiner/assets/44615981/a2e7b84b-b94c-4534-b4d3-a257fd857b6b">

The issue is, that after linking this repo config to the karabiner it can't to access this file fully, as I understand.

**Comment by mxstbr** [comment] 2024-04-18 12:35
Closing. Let me know if that fix doesn't work!

**Closed** 2024-04-18 12:35 UTC

**Comment by mannerisms** [comment] 2024-04-18 13:51
First, thanks for this awesome idea and for sharing. I think this is the right thread, but just to ensure that I understand completely. Is it correct that after the caps hyperkey was changes from specific:
```
          "to": [
            {
              "key_code": "left_shift",
              "modifiers": [
                "left_command",
                "left_control",
                "left_option"
              ]
            }
```
To the current useage of a variable, the hyperkey now, if pressed and held alone no longer gets registered in MacOS as '⌃⌥⇧⌘'

I think that is what is causing some confusion with me and with others, that when implementing this repo, all hyperkey functions must now be configured in karabiner as e.g. 'Hyper+T' can no longer be set as a shortcut in Raycast.

Thanks again!

**Comment by daun** [comment] 2024-04-18 15:22
I can conform this is an issue on the latest MacOS Sonoma 14.4.1. The key combination works when pressing all three keys at the same time, e.g. `Hyper` + `R` + `E` for the emoji picker, but the staggered workflow of `Hyper` + `R`, followed by `E` does not work. Tried on two different Macs, one with Karabiner installed via the download from their website, one installed via homebrew. Tried the fix above, restarted a few times, doesn't seem to work.

**Comment by mxstbr** [comment] 2024-04-18 15:23
The staggered workflow has never worked. You have to press the key combination in one, together.

**Comment by mxstbr** [comment] 2024-04-18 15:24
I have moved all my Hyperkey shortcuts from Raycast to Karabiner, so I can see why I wouldn't have noticed that it breaks other Hyperkey usages 🙈 

You should be able to replace all your hyperkey usage with Karabiner.

**Comment by daun** [comment] 2024-04-18 15:31
@mxstbr I see, in that case it's working as expected! And it's actually much more ergonomic that way for most key combinations like the window management layer :)

**Comment by lawsonguilbeau** [comment] 2024-04-18 21:31
@sluzhynskyi, thank you for the suggestion, I will have to try it out. The thing I am wondering however, is how you got the karabiner_grabber file to have full disk access.

**Comment by lawsonguilbeau** [comment] 2024-04-18 22:26
I figured it out. Thanks for all the help though.

**Comment by mannerisms** [comment] 2024-04-19 09:30
Yeah it makes sense now, thanks again!

**Comment by m-collins** [comment] 2024-04-28 06:22
I burnt a bit of time on this today due to the issue on Sonoma. Given this is isn't part of the standard KE install, It could be helpful to include this step in the Readme
